version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://fintech_user:secure_password_123@db:5432/fintech_db
      LOG_LEVEL: debug
      ENV: development
      PORT: 8000
      MAX_WORKERS: 2
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
    depends_on:
      - db
    networks:
      - fintech_network

  db:
    image: postgres:16-alpine
    platform: linux/arm64/v8  # Optimized for Apple Silicon (M4)
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fintech_user -d fintech_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fintech_network

volumes:
  db_data:

networks:
  fintech_network:
    driver: bridge