definitions:
  models.BalanceResponse:
    properties:
      balance:
        type: number
      total_credits:
        type: number
      total_debits:
        type: number
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - Health
  /migrate:
    post:
      consumes:
      - multipart/form-data
      description: Upload a CSV file to migrate transactions. Returns the number of
        skipped rows and a success message.
      parameters:
      - description: CSV file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Migration successful
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Migrate transactions from a CSV file
      tags:
      - Migration
  /users/{user_id}/balance:
    get:
      description: Retrieves the balance for a specific user, optionally filtered
        by date range.
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: Start date in RFC3339 format
        in: query
        name: from
        type: string
      - description: End date in RFC3339 format
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BalanceResponse'
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user balance
      tags:
      - balance
swagger: "2.0"
